seed_everything: 42

data:
  class_path: "src.data.DataModule"
  init_args:
    train_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024/train"
    val_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024-full/val"
    test_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024-full/test"
    batch_size: 8
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1.0
        seed: 42
        transforms:
          - __class_fullname__: RandomCrop
            border_mode: 0
            fill: 0.0
            fill_mask: 0.0
            height: 1024
            p: 1.0
            pad_if_needed: true
            pad_position: center
            width: 1024
          - __class_fullname__: ToFloat
            max_value: 255.0
            p: 1.0
          - __class_fullname__: SquareSymmetry
            p: 1.0
          - __class_fullname__: RandomBrightnessContrast
            brightness_by_max: false
            brightness_limit:
              - -0.2
              - 0.2
            contrast_limit:
              - 0.0
              - 0.0
            ensure_safe_range: false
            p: 0.3
          - __class_fullname__: CoarseDropout
            fill: 0.0
            fill_mask: 0.0
            hole_height_range:
              - 0
              - 32
            hole_width_range:
              - 0
              - 32
            num_holes_range:
              - 1
              - 8
            p: 0.5
          - __class_fullname__: Normalize
            max_pixel_value: 1.0
            normalization: min_max
            p: 1.0
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false
    test_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: PadIfNeeded
            border_mode: 0
            fill: 0.0
            fill_mask: 0.0
            min_height: 1024
            min_width: 1024
            p: 1.0
            pad_height_divisor: null
            pad_width_divisor: null
            padding: 0
            position: center
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            normalization: min_max
            p: 1.0
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

model:
  class_path: "src.models.kom_port.KomRGBISpeciesBaselineModel"
  init_args:
    num_classes: 3
    ignore_index: &ignore_index -100
    optimizer_class: torch.optim.AdamW
    optimizer_opts:
      lr: 3e-1
      weight_decay: 0.01
      betas:
        - 0.9
        - 0.95
    lr_scheduler_class: torch.optim.lr_scheduler.CosineAnnealingLR
    lr_scheduler_interval: step
    loss: "LovaszLoss"
    loss_opts:
      mode: "multiclass"
      ignore_index: *ignore_index
      from_logits: false

trainer:
  accelerator: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 10
  gradient_clip_val: 1.0
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: false
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: hakai
        project: kom-kelp-rgbi
        name: kom-port-v0.13.1
        group: Jul2025
        log_model: true
        tags:
          - kelp
          - Jul2025
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
